### PR TITLE
chore: Add disabled property for context-menu

### PR DESCRIPTION
**Pull request by nicksangeorge**
[Jira Card](https://kubprojects.atlassian.net/browse/KUBAPPS-827?atlOrigin=eyJpIjoiODFkMzZiMDVhNDNhNGUzOGE2YTUxMTc4MzMxZGI4ZDYiLCJwIjoiaiJ9)

[Related PR](http://github.kub.org/web/ember-kubapps-ui/pull/446)

### CODE REVIEW

**Review by TSenter — CHANGES_REQUESTED** [review]
Could you add a test for this? Or at least attach a screenshot in a comment showing what it looks like when it's disabled - you should be able to do this in the Ember Inspector

**Comment by nicksangeorge** [comment]
> Could you add a test for this? Or at least attach a screenshot in a comment showing what it looks like when it's disabled - you should be able to do this in the Ember Inspector

image

When disabled, it shows as greyed out.

**Comment by fdlane** [comment]
@nicksangeorge @TSenter  I like the idea of a test for this.  Let's try to include one in this pr

**Comment by TSenter** [comment]
@fdlane, Nick and I talked and we thought it would be best to get this PR merged and complete before he's gone, so I will have a separate PR for tests for this (and possibly other things) soon. We met and worked on it together, but there's a problem with one of the test helpers that I'll have to come back to.

**Review by TSenter — APPROVED** [review]

**Pull request merged**
